### ISSUE TITLE
Would like to help

### ISSUE THREAD

**Issue by RandalSchwartz** [cranst0n/ribs#14]
I initially shrugged at this, thinking that fpdart was light-years ahead.

But I've been grepping through the code, and I like what I'm seeing.

I'd like to help.  You need some bigger examples, and more docs.

Are you on social media anywhere?  I'm everywhere, so feel free to close this ticket and ping me anywhere.

**Comment by cranst0n** [comment]
Sorry I just saw this now. I'm on twitter and discord (cranst0n). Please feel free to reach out!
